# RedGreen provides the core namespace for the Roslyn red/green tree port.
require "./red_green/node_flags"
require "./red_green/green_node"
require "./red_green/syntax_node"
require "./red_green/syntax_tree"
require "./red_green/syntax_token"
require "./red_green/syntax_trivia"
require "./red_green/syntax_node_or_token"
require "./red_green/child_syntax_list"
require "./red_green/child_syntax_list_with_tokens"
require "./red_green/syntax_token_list"
require "./red_green/syntax_trivia_list"
require "./red_green/syntax_walker"
require "./red_green/syntax_differ"
require "./red_green/syntax_factory"
require "./red_green/syntax_annotation"
require "./red_green/text_span"
require "./red_green/diagnostics"
require "./red_green/source_text"
require "./red_green/text_cursor"
require "./red_green/lexer"
require "./red_green/parser"
require "./red_green/line_position"
require "./red_green/text_line"
require "./red_green/location"
require "./red_green/diagnostic_descriptor"
require "./red_green/syntax_kind_helpers"
require "./red_green/structured_trivia"
require "./red_green/directives"
require "./red_green/skipped_text"
require "./asdl"
require "./red_green/syntax_list"
require "./red_green/separated_syntax_list"
require "./red_green/internal_syntax/syntax_list"
require "./red_green/internal_syntax/syntax_list_variants"
require "./red_green/internal_syntax/green_token"
require "./red_green/internal_syntax/green_trivia"
require "./red_green/syntax_node_cache"
require "./red_green/green_node_builder"

module RedGreen
  VERSION = "0.1.0"
end
